apiVersion: v1
kind: Service
metadata:
  name: hydrify-service
spec:
  type: NodePort
  selector:
    app: hydrify
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
